from typing import List, Protocol
from uuid import UUID
from app.domain.entities.task import Task


class ITaskRepository(Protocol):
    async def add(self, task: Task) -> None: ...
    async def list(self) -> List[Task]: ...
    async def list_by_user(self, user_id: UUID) -> List[Task]: ...
    async def get(self, task_id: UUID) -> Task | None: ...
    async def update(self, task: Task) -> Task: ...
    async def delete(self, task_id: UUID) -> None: ...
